version: '3.8'
services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: app_delivery_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    restart: always
